# Generated by Django 3.1.6 on 2021-03-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedorApp', '0001_initial'),
        ('gruposApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='proveedorApp.proveedor'),
        ),
    ]
