# Generated by Django 3.1.6 on 2021-02-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruposApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBoleta', models.CharField(max_length=9)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('GrupoPerteneciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gruposApp.grupo')),
            ],
        ),
    ]
