# Generated by Django 3.1.6 on 2021-02-17 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zapatillasApp', '0005_zapatilla_vendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField()),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipoPago', models.CharField(max_length=20)),
                ('zapatillaCorrespondiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.zapatilla')),
            ],
        ),
    ]
