# Generated by Django 3.1.6 on 2021-02-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruposApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=4)),
                ('precioSugerido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioCompra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoriaGenero', models.CharField(max_length=7)),
                ('categoriaUso', models.CharField(max_length=7)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('colorPrincipal', models.CharField(max_length=10)),
                ('colorSecundario', models.TextField(blank=True, default='')),
                ('grupoPerteneciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruposApp.grupo')),
            ],
        ),
    ]
