# Generated by Django 3.1.6 on 2021-02-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillasApp', '0003_zapatilla_marcaperteneciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='marcaPerteneciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.marca'),
        ),
    ]
