# Generated by Django 3.1.6 on 2021-02-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillasApp', '0004_auto_20210216_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
